# overlays/stg/kustomization.yaml
namespace: ambiente-atale-stg


resources:
  - ../../base
  - hpa.yaml

patchesStrategicMerge:
  - patch-backend-deployment.yaml
  - patch-frontend-deployment.yaml
  - patch-secret.yaml
  - patch-configmap.yaml
